### PR TITLE
Allow Bazel 2.2.0 in start script

### PR DESCRIPTION
**Pull request by hanshoglund**

### CODE REVIEW

**Comment by hanshoglund** [comment]
Hold that thought, seems I need to bump `versions.bzl` as well.

**Comment by Profpatsch** [comment]
Hm, what’s the status?

**Comment by hanshoglund** [comment]
Sorry, this fell off my radar. Will close as there is no real progress. Let's create a new ticket for the next version bump.

**Comment by aherrmann** [comment]
https://github.com/tweag/rules_haskell/pull/1395 would cover 2.2.0 as well.

**Pull request closed without merging**
