### PR TITLE
WIP: Add a `haskell_group` target

### LINKED ISSUE #753: Add a `filegroup`-like rule for haskell targets
While refactoring a codebase, I tried to internally split some packages while keeping the same interface, *i.e* structure them as follows:

```bzl
haskell_library(
  name = "sub-lib1",
  …,
  visibility = ["//visibility:private"],
)

haskell_library(
  name = "sub-lib2",
  …,
  visibility = ["//visibility:private"],
)

haskell_library(
  name = "sub-lib3",
  …,
  visibility = ["//visibility:private"],
)

filegroup(
  name = "mylib",
  srcs = [ ":sub-lib1", ":sub-lib2", ":sub-lib3" ],
  visibility = ["//visiblity:public"],
)
```

so that the dependencies which used to depend on `//mylib:mylib` can continue to do so and the split remains internal.

However using a `filegroup` for that doesn't work since it won't forward the `HaskellLibraryInfo` providers and thus `//mylib:mylib` won't be recognized as a set of haskell deps and will be ignored.

This led me to the idea of a `haskell_target_group` rule which would combine a set of `haskell_library`/`haskell_binary` targets (meaning properly combine the `HaskellLibrary`/`HaskellBinary` providers so that it looks like a single target from the outside)

In addition to the pattern above, this would give "for free" a multi-targets repl rule (actually this would probably borrow a lot of the implementation from #736 and make the actual repl rule just a thin layer on top of it)

### PR DESCRIPTION
**Pull request by regnat**
Bundles together a list of `haskell_library` targets so that they appear as a single one from the outside.

### TODO

- [X] Initial implementation
- [X] Add a `@repl` target to the group
- [ ] Add tests
- [ ] Allow bundling `haskell_binary` targets

Fix #753

### CODE REVIEW

**Comment by mboes** [comment]
I would prefer following precedent established by core rules where it exists. Consider what the CC rules allow:

```python
cc_library(
    name = "foo",
    srcs = ["foo.c"],
)

cc_library(
    name = "bar",
    srcs = ["bar.c"],
)

cc_library(
    name = "baz",
    deps = [":foo", ":bar"],
)

cc_binary(
    name = "main",
    srcs = ["main.c"],
#    deps = [":baz"],
)
```

The build fails. If you uncomment the last line, then it works. So `cc_library` is a monoid under `deps` composition (you can have an empty `cc_library` as well).

**Comment by regnat** [comment]
> So cc_library is a monoid under deps composition

That would mean making any indirect dependency a direct dependency, right? Wouldn't that be a (potentially quite annoying) breaking change? Because haskell doesn't impose that your modules are unique within your transitive dependency graph, but only that they are unique within your direct dependency graph.

For example, consider that `foo` depends on `hashmap` and `bar` depends and `foo` and `unordered-containers`. Both `hashmap` and `unordered-containers` expose the `Data.HashMap` module, but `bar` can import it without ambiguity because it doesn't directly depend on `hashmap` so the compiler knows that the `Data.HashMap` it imports comes from `unordered-containers`.
Now if we flatten the dependency graph, this doesn't hold anymore and unless we use the syntactically heavy `PackageImport` we can't import `Data.HashMap` anymore.


What we could have is something similar to nix's `buildInput` and `propagatedBuildInputs` where we explicitely specify which inputs are exposed to the dependent packages

**Comment by aherrmann** [comment]
> What we could have is something similar to nix's buildInput and propagatedBuildInputs where we explicitely specify which inputs are exposed to the dependent packages

That's an interesting idea. There's precedent for this kind of behavior in the builtin Java rules and rules_scala with the [`exports` attribute](https://docs.bazel.build/versions/master/be/java.html#java_library.exports).

It's also worth pointing out that the Java rules do explicitly not follow the monoid model in the `deps` attribute (emphasis mine):

> Listing rules here will make them available to parent rules, as if the parents explicitly depended on these rules. **This is not true for regular (non-exported) deps.**

---

> So cc_library is a monoid under deps composition (you can have an empty cc_library as well).

If rules_haskell were to follow that model, how would this interact with `cc_library` dependencies? In the past [it was decided]( https://github.com/tweag/rules_haskell/issues/531#issuecomment-449052316) that only header files of direct C library dependencies should be visible. By the monoid logic it seems that also headers of indirect dependencies should be visible.

> If final directly refer to a.h, it MUST depends on :cbits, that's not an indirect dependency, that's a direct dependency and it should be listed as such. Adding :cbits as dependencies of final fix the build.

**Comment by mboes** [comment]
We already have an `exports` attribute: http://api.haskell.build/haskell/haskell.html#haskell_library.exports.

**Comment by regnat** [comment]
But the `exports` attribute that we have isn't the same as the `export` attribute from java rules because it's much more granular

**Comment by mboes** [comment]
Arguably the `exports` attribute that we have was misnamed. It's about modules whereas Java's is about libraries, i.e. the Java one talks about targets whereas ours does not. I'm not sure that anyone as using the `exports` attribute yet apart from maybe @lunaris, so depending on his input we could consider a BC here (will be a lot harder down the line).

**Comment by lunaris** [comment]
@mboes I don't think we're using this feature so have no objections from that point of view. I must confess though, while I see the benefits this could bring for refactoring (as an analog to `filegroup`), I have reservations about its use in supporting REPLs across multiple libraries. Naturally I'm biased, but we (Habito) ended up building a solution atop #695 that I think works quite well (and e.g. we are using to support `ghcid` etc. too) -- this is preferable to me since it doesn't require defining anything like `haskell_repl` / `haskell_group` up front. But I appreciate I'm perhaps missing the true point of `haskell_group` here/lacking understanding around limitations of REPL targets in general.

**Comment by regnat** [comment]
> I have reservations about its use in supporting REPLs across multiple libraries

As far as I'm concerned, the REPL thing was just a happy side-effect, which is anyways superseded by #736 and (I think) wouldn't make sense with the "forward transitive dependencies" approach.

But if nobody has any objection against changing the `exports` attribute I think we can go on.
@mboes should we keep the old attribute under a new name or remove it altogether? (afair it had been introduced in an effort to support backpack, but I don't think there has been much advances on that front)

**Comment by mboes** [comment]
I think we should expose it under a new name. It's exposing a feature of GHC that predates Backpack (and independently useful, though rarely so).

**Comment by Profpatsch** [comment]
Ping: what’s the status of this PR?

**Comment by regnat** [comment]
> Ping: what’s the status of this PR?

I'll take a few hours this week to update it, it has been stalled for too long

**Comment by Profpatsch** [comment]
Have we decided we want this feature?

**Comment by regnat** [comment]
Closing since I'm not needing this anymore and nobody else seems to want to use it atm

**Pull request closed without merging**
