### PR TITLE
Check if haddock paths exists

### LINKED ISSUE #1075: haskell_doc fails if sub-package does not provide documentation
**Describe the bug**

This is a new incarnation of #335.

If `haskell_doc` references a package which does not provide a `.haddock` file, it fails.

I bisected the regression to this commit: ff669231cf63fcbc631c91e694254cfb7d35db71

I think the logic of checking if the path exists was removed in that commit. I'll open a PR with the added check. @mboes, you did the commit, do you remember if there is any reason to remove the check?

**To Reproduce**

Build an `haskell_doc` which point to a library which does not have a `.haddock` file. I'll come with a repro later if the PR takes more time than expected.

### PR DESCRIPTION
**Pull request by guibou**
ghc package database may contain not existing paths, we check that they
really exists before writing them in bazel database.

Closes #1075

### CODE REVIEW

**Comment by guibou** [comment]
@Profpatsch can this reach the release?

**Comment by Profpatsch** [comment]
I’d do a major release now and then a patch release in a few days, with all the new `stack_snapshot` improvements. I suggest we put this in then, too.

**Comment by guibou** [comment]
Ok.

**Comment by aherrmann** [comment]
CI fails with
```
ERROR: /var/lib/buildkite-agent/builds/ubuntu-32gb-nbg1-1-1/tweag-1/rules-haskell/tests/BUILD.bazel:198:1: in _rule_test_rule rule //tests:test-haddock_impl:
--
  | Traceback (most recent call last):
  | File "/var/lib/buildkite-agent/builds/ubuntu-32gb-nbg1-1-1/tweag-1/rules-haskell/tests/BUILD.bazel", line 198
  | _rule_test_rule(name = 'test-haddock_impl')
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/705e91a3c3f91a5bd34340f15a121385/external/bazel_tools/tools/build_rules/test_rules.bzl", line 296, in _rule_test_rule_impl
  | fail(("rule %s generates %s not %s" %...))))
  | rule //tests/haddock:haddock generates ["haddock/index", "haddock/testsZShaddockZShaddock-lib-a", "haddock/testsZShaddockZShaddock-lib-b", "haddock/testsZShaddockZShaddock-lib-deep"] not ["haddock/array-0.5.3.0", "haddock/base-4.12.0.0", "haddock/deepseq-1.4.4.0", "haddock/ghc-boot-th-8.6.5", "haddock/ghc-prim-0.5.3", "haddock/index", "haddock/integer-gmp-1.0.2.0", "haddock/pretty-1.1.3.6", "haddock/template-haskell-2.14.0.0", "haddock/testsZShaddockZShaddock-lib-a", "haddock/testsZShaddockZShaddock-lib-b", "haddock/testsZShaddockZShaddock-lib-deep"]
```
https://buildkite.com/tweag-1/rules-haskell/builds/273#e03e6f39-4b73-403f-bab3-7cb76ddb9ce3/14-73

Looks like that test case expects haddocks for core-packages which are not generated.

**Comment by guibou** [comment]
Considering that there is some differences between bindist and another way of getting ghc, I'm considering the following options:

- Disable this test
- Enable this test only for nixpkgs
- previous one + create another test only for bindist.

I'm in favor of the last one, do you have an opinion?

**Comment by aherrmann** [comment]
@guibou I'd also favor the last one.

**Comment by Profpatsch** [comment]
I’ll see whether I can get this ready for merge today.

**Comment by Profpatsch** [comment]
After rebasing on master, the bindists fail on missing `.haddock` headers: 

https://buildkite.com/tweag-1/rules-haskell/builds/523#76c4ddb5-add0-4933-bf53-294a68897630/16-3239

I guess the assumptions in this PR are not correct? Especially the symlinking.
It’s hard for me to infer the intended file structure from the code. How are the haddock directories supposed to look?

**Comment by Profpatsch** [comment]
Closing for now, because some more work is needed to fix this.

**Pull request closed without merging**
