### PR TITLE
chore: upgrade Bazel to 6.5.0

### PR DESCRIPTION
**Pull request by cgrindel**

### CODE REVIEW

**Comment by cgrindel** [comment]
Ugh. I forgot about the Nix tests. I will need to see if someone has upgrade bazel_6.

**Comment by avdv** [comment]
> Ugh. I forgot about the Nix tests. I will need to see if someone has upgraded `bazel_6`.

I tried to, but ran into problems on Darwin. See https://github.com/NixOS/nixpkgs/pull/283480

**Comment by avdv** [comment]
Picking this up again, after Bazel 6.5.0 landed in nixos-unstable :tada:

**Review by avdv — APPROVED** [review]

**Comment by avdv** [comment]
@mergifyio rebase

**Comment by avdv** [comment]
@mergifyio rebase

**Pull request merged**
