### PR TITLE
Support protobuf roots in haskell_proto_library rules

### PR DESCRIPTION
**Pull request by andyscott**
This is a stab at fixing #717, which boils down to two problems:
1. (easy) The capitalization logic mishandles paths that begin or end with a delimiter character.
2. (harder) The protobuf rules don't support 'protobuf source roots', which handles the various mappings bazel does for import paths.

I've tested this against my larger project and it seems to work fine, so far :).

### CODE REVIEW

**Comment by andyscott** [comment]
I suppose I should note that this only works for Bazel 0.22.0 onwards.

**Comment by Profpatsch** [comment]
> I suppose I should note that this only works for Bazel 0.22.0 onwards, as `strip_import_prefix` didn't exist before then (see [bazel commit](https://github.com/bazelbuild/bazel/commit/8191c62f71ea99b8f9ebb7816e8cec926f14c888)).

That’s fine, current master is 0.22 upwards.

**Comment by andyscott** [comment]
The one failing test seems to be running on bazel 0.21.0:
```
#!/bin/bash -eo pipefail
apt-get update
apt-get install -y wget gnupg golang make libgmp3-dev pkg-config zip g++ zlib1g-dev unzip python bash-completion locales
echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
locale-gen
wget "https://github.com/bazelbuild/bazel/releases/download/0.21.0/bazel_0.21.0-linux-x86_64.deb"
dpkg -i bazel_0.21.0-linux-x86_64.deb
echo "common:ci --build_tag_filters -requires_hackage,-requires_zlib,-requires_doctest,-requires_c2hs,-requires_threaded_rts,-dont_test_with_bindist" > .bazelrc.local
```
With a missing attribute error:
```
#!/bin/bash -eo pipefail
bazel build --config ci //tests/...
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 0aa3e72d-a01e-4d48-9763-3c3942f8e255
Loading: 
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
ERROR: /root/rules_haskell/tests/haskell_proto_library/BUILD:30:1: //tests/haskell_proto_library:stripped_zip_code_proto: no such attribute 'strip_import_prefix' in 'proto_library' rule
ERROR: /root/rules_haskell/tests/haskell_proto_library/BUILD:36:1: //tests/haskell_proto_library:stripped_address_proto: no such attribute 'strip_import_prefix' in 'proto_library' rule
ERROR: package contains errors: tests/haskell_proto_library
ERROR: error loading package 'tests/haskell_proto_library': Package 'tests/haskell_proto_library' contains errors
INFO: Elapsed time: 5.031s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (61 packages loaded)
FAILED: Build did NOT complete successfully (61 packages loaded)
Exited with code 1
```

**Comment by Profpatsch** [comment]
Will set up 0.22 with the CI on Monday.

**Comment by Profpatsch** [comment]
Pushed an update to the bindists

**Pull request merged**
