### PR TITLE
Fix darwin bindist by touching WORKSPACE file

### PR DESCRIPTION
**Pull request by Profpatsch**
Closes: https://github.com/tweag/rules_haskell/issues/884

### CODE REVIEW

**Comment by mboes** [comment]
How does this work?

**Comment by Profpatsch** [comment]
> How does this work?

Some rule tried to access `io_tweag_rules_haskel_ghc_darwin_amd64` as a bazel repository, but without a `WORKSPACE` file things are not counted as repository. If we `touch` it, it’s recognized as a repository. I am not 100% certain it *should* be counted as a repository, so please stop me if that’s wrong.

**Comment by mboes** [comment]
This looks suspicious to me. Are you sure it works with this patch but fails without? Also, Bazel tends to automatically generate a `WORKSPACE` file for external repositories.

**Comment by Profpatsch** [comment]
I’ll try what happens if I remove this patch (once I can access the test Macbook again)

**Comment by mboes** [comment]
Easiest is to ssh into circleci workers

**Pull request merged**
