### PR TITLE
Missing source_files argument to HaskellInfo

### PR DESCRIPTION
**Pull request by guibou**
Recent refactors missed these lines.

### CODE REVIEW

**Comment by guibou** [comment]
Indeed. I'll add them too.

**Comment by guibou** [comment]
@m is the current CI failure due to the "red" master we had previously?

**Comment by mboes** [comment]
Yes, rebase.

**Comment by guibou** [comment]
@aherrmann other missing attributes added.

**Comment by guibou** [comment]
I'm sure it will confilt with #900 (set removal work). I'm waiting for it to be merged.

**Comment by guibou** [comment]
@mboes that's rebased, however I'm suprised that `source_files` and `import_dirs` are still set, considering your recent changes.

**Pull request merged**
