### PR TITLE
Migrate to the modern linker input API.

### PR DESCRIPTION
**Pull request by benjaminp**
See https://github.com/bazelbuild/bazel/issues/10860.

### CODE REVIEW

**Review by mboes — APPROVED** [review]

**Comment by mboes** [comment]
LGTM, but assigning @aherrmann for an additional review.

**Review by aherrmann — COMMENTED** [review]
Thank you!

Should [this instance](https://github.com/benjaminp/rules_haskell/blob/318c530609fed1d7629746f9b705eed65e8e7abf/haskell/private/cc_libraries.bzl#L307) also be changed or is there a reason to keep using `libraries_to_link` in that case?

Did you try enabling `--incompatible_require_linker_input_cc_api` in [`.bazelrc`](https://github.com/benjaminp/rules_haskell/blob/318c530609fed1d7629746f9b705eed65e8e7abf/.bazelrc#L58)? Would be good to check against regressions on this on CI if possible.

**Comment by benjaminp** [comment]
> Thank you!

Thank you for the review.

> 
> Should [this instance](https://github.com/benjaminp/rules_haskell/blob/318c530609fed1d7629746f9b705eed65e8e7abf/haskell/private/cc_libraries.bzl#L307) also be changed or is there a reason to keep using `libraries_to_link` in that case?

Yes, indeed! This makes me realize I accidentally pushed an old version of my branch that didn't fix that case through a git snafu. Should be okay now.

> 
> Did you try enabling `--incompatible_require_linker_input_cc_api` in [`.bazelrc`](https://github.com/benjaminp/rules_haskell/blob/318c530609fed1d7629746f9b705eed65e8e7abf/.bazelrc#L58)? Would be good to check against regressions on this on CI if possible.

Yes, that's how I was testing locally. I committed this to the branch now, too.

**Review by aherrmann — APPROVED** [review]
Thank you!

**Comment by aherrmann** [comment]
@Mergifyio rebase

**Pull request merged**
