### PR TITLE
Set experiments

### LINKED ISSUE #77: Use skylib's _uniq over depset(foo).to_list()
We uses `depset(foo).to_list()` in many places to get unique elements of `foo`. Skylib offers this in a much faster way: build a dictionary with None values then use `.keys()`: apparently depsets do _not_ support fast membership check and to_list() is definitely bad.

Minor ticket but simple.

### PR DESCRIPTION
**Pull request by mrkkrp**
Close #77.

### CODE REVIEW

**Comment by mrkkrp** [comment]
This appears to decrease the percent of time spent in `depset`. No set-related function reaches even 1% of time in my experiments. Absolute values are subject to considerable fluctuation.

**Comment by mboes** [comment]
It's unclear to me what the conclusion is here perf wise. Can you write down some actual numbers and how you got them?

**Comment by mrkkrp** [comment]
## How to obtain the results

The results presented below may be obtained in the following way:

* Clone, build, and install [spit-haskell-rules].
* Make a new directory `cd` into it, and populate it with a dummy repo:

  ```
  $ mkdir profiling
  $ cd profiling
  $ spit-haskell-rules -d 100 -w 100
  ```
  This will generate a repo with 10 000 packages which depend on each other in the way described in the readme of [spit-haskell-rules].

* To profile the `master` branch (i.e. depsets version), execute:

  ```
  $ bazel build --nobuild --profile=depset.out :39e5b4830d4d9c14db7368a95b65d5463ea3d09520373723430c03a5a453b5df
  $ bazel analyze-profile depset.out --html --html_details
  ```

* To profile the `set-experiments` branch, edit `WORKSPACE` file accordingly either using `local_repository` to point to local copy of `rules_haskell` with the `set-experiments` branch checked out, or edit the name of branch in the existing `http_archive`. Then proceed as usual:

  ```
  $ bazel build --nobuild --profile=set.out :39e5b4830d4d9c14db7368a95b65d5463ea3d09520373723430c03a5a453b5df
  $ bazel analyze-profile set.out --html --html_details
  ```
## The results

With 10 000 packages the profiling results seem to be more or less reproducable. Sets are depsets perform almost the same:

|        | Total execution time | 
| ------ | -------------------- |
| Depset | 14.786               |
| Set    | 14.048               |


Top user-defined functions with depsets:

| # | Function              | Total      | Relative (%) |
|---|:----------------------|-----------:|-------------:|
| 1 | _haskell_library_impl | 75,087.905 | 32.523%      |
| 2 | compile_haskell_lib   | 27,923.646 | 12.095%      |
| 3 | create_ghc_package    | 26,986.995 | 11.689%      |
| 4 | compilation_defaults  | 18,974.631 | 8.218%       |

Top built-in functions with depsets:

| # | Function              | Total      | Relative (%) |
|---|:----------------------|-----------:|-------------:|
| 1 | depset                | 3,326.617  | 30.778%      |
| 2 | join                  | 1,667.174  | 15.425%      |
| 3 | format                | 1,197.12   | 11.076%      |
| 4 | add                   | 1,069.089  | 9.891%       |

Top user-defined functions with sets:

| # | Function              | Total      | Relative (%) |
|---|:----------------------|-----------:|-------------:|
| 1 | _haskell_library_impl | 69,216.406 | 31.774%      |
| 2 | compile_haskell_lib   | 29,611.637 | 13.593%      |
| 3 | compilation_defaults  | 20,620.454 | 9.466%       |
| 4 | create_ghc_package    | 16,858.272 | 7.739%       |

Top built-in function with sets:

| # | Function              | Total      | Relative (%) |
|---|:----------------------|-----------:|-------------:|
| 1 | format                | 2,327.287  | 18.935%      |
| 2 | depset                | 2,257.03   | 18.363%      |
| 3 | join                  | 2,247.517  | 18.286%      |
| 4 | update                | 1,322.728  | 10.762%      |

That said, I fail to see how the thing we're measuring can be a bottleneck, because the time spent manipulating depsets or sets is negligible compared to the time spent running `ghc` and other executables. Maybe I'm missing something here, but the main benefit with sets is just nicer code, it's good to have them in your toolbox and they are occasionally useful.

[spit-haskell-rules]: https://github.com/mrkkrp/spit-haskell-rules

**Comment by mboes** [comment]
The important thing to avoid is any quadratic scaling, which can happen quite quickly in a build system, as discussed [here](https://docs.bazel.build/versions/master/rule-challenges.html#intrinsic-avoiding-quadratic-time-and-memory-consumption-is-hard) and [here (last paragraph)](https://docs.bazel.build/versions/master/skylark/depsets.html#performance).

I feel decidedly neutral about whether the code with sets ends up nicer than the code with depsets. Avoiding our own custom collection type does mean less code. So I'll leave it to @Fuuzetsu to decide.

**Review by Prlk12 — COMMENTED** [review]
haskell/actions.bzl

**Pull request merged**
