### PR TITLE
Fix all_files captures "bazel-*" directories

### PR DESCRIPTION
**Pull request by k1nkreet**
Fix for #1673

### CODE REVIEW

**Review by aherrmann — APPROVED** [review]
Thank you for fixing this so quickly!

**Comment by k1nkreet** [comment]
There is a problem with Mergify configuration got deprecated today afaiu: https://blog.mergify.com/strict-mode-deprecation/

**Comment by aherrmann** [comment]
> There is a problem with Mergify configuration got deprecated today afaiu: https://blog.mergify.com/strict-mode-deprecation/

Indeed, looks like it. I think the Mergify config on rules_sh uses the new format and could probably be adapted for rules_sh as well. See https://github.com/tweag/rules_sh/blob/master/.mergify.yml.

**Comment by aherrmann** [comment]
Looks like mergify still uses the configuration from master. But, I've checked the new config in the [dashboard](https://dashboard.mergify.com/github/tweag/repo/rules_haskell/config-editor?repositoryName=rules_haskell&pullRequestNumber=1674) and it looks good.
So, merging manually...
@k1nkreet thank you!

**Pull request merged**
