### PR TITLE
Disable sandboxing on doctest tests to prevent race condition

### PR DESCRIPTION
**Pull request by gdeest**
There are occasional race conditions issues on Linux with doctest tests. The issue seems related to sandboxing (cf. #620 ).

This PR fixes this issue by selectively disabling sandboxing on those tests.

### CODE REVIEW

**Comment by gdeest** [comment]
CI currently read because of linter. I can't run `buildifier-fix` locally (cf. #616 ).

**Comment by regnat** [comment]
Isn't there a cleaner solution for fixing these tests? I remember we had the same issue with haddock and we could fix it by explicitely specifying the temp directory. Isn't it something that we can fix the same way?

**Comment by gdeest** [comment]
@regnat 

Indeed, I am not too happy about it either, but `doctest` does not support being passed an explicit directory. I have filed an issue here: https://github.com/sol/doctest/issues/219

In the mean time, disabling sandboxing for those tests seems reasonable to me, but I am open to better ideas.

**Comment by mboes** [comment]
@gdeest could you include a link to the issue you created in the source code? That way if it gets fixed then we'll eventually move the code to a cleaner solution.

**Pull request merged**
