### PR TITLE
Merge rules_haskell_examples into this repo

### PR DESCRIPTION
**Pull request by Profpatsch**
This merges https://github.com/tweag/rules_haskell_examples and applies a few fixup commits, while keeping the original history of that repo.

The last few commits by me are relevant for review.

Relevant step for https://github.com/tweag/rules_haskell/issues/698

### CODE REVIEW

**Comment by Profpatsch** [comment]
Fixes https://github.com/tweag/rules_haskell_examples/issues/14

**Comment by mboes** [comment]
@Profpatsch I removed a few of your patches, which turned out unnecessary. The workaround was to move the tutorial directory out of examples.

This PR now depends on #737.

**Comment by Profpatsch** [comment]
Meh, I guess I was too deep in, trying to work around `WORKSPACE` deficiencies, to think about the obvious solution.

Should do a repro and create an upstream bug report nonetheless.

**Comment by Profpatsch** [comment]
Though we have to check in complete copies of `vector` and multiple other libraries though? This makes grepping through `rules_haskell` extremely noisy.

**Comment by Profpatsch** [comment]
(rebased with //:buildifier-fix)

**Comment by mboes** [comment]
These are vendored dependencies. Common practice (including in Bazel itself). `grep <pattern> haskell` in any case. We could download sdists from Hackage instead, but those would be external repos, hence recursive workspace problem again.

**Pull request merged**
