### PR TITLE
Add Bazel 5 to the integration testing on CI

### PR DESCRIPTION
**Pull request by k1nkreet**

### CODE REVIEW

**Comment by k1nkreet** [comment]
Okay, I found this in the actions log:
```
Unhandled exception. System.IO.IOException: No space left on device : '/home/runner/runners/2.294.0/_diag/Worker_20220713-122305-utc.log'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at System.Diagnostics.TraceSource.Flush()
   at GitHub.Runner.Common.TraceManager.Dispose(Boolean disposing)
   at GitHub.Runner.Common.TraceManager.Dispose()
   at GitHub.Runner.Common.HostContext.Dispose(Boolean disposing)
   at GitHub.Runner.Common.HostContext.Dispose()
   at GitHub.Runner.Worker.Program.Main(String[] args)
System.IO.IOException: No space left on device : '/home/runner/runners/2.294.0/_diag/Worker_20220713-122305-utc.log'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
   at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
   at GitHub.Runner.Worker.Worker.RunAsync(String pipeIn, String pipeOut)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
System.IO.IOException: No space left on device : '/home/runner/runners/2.294.0/_diag/Worker_20220713-122305-utc.log'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
   at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
   at GitHub.Runner.Common.Tracing.Error(Exception exception)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
```
@aherrmann Do you have any idea where it could come from?

**Comment by k1nkreet** [comment]
it's linux-bindist which is marked as skipped for some reason, I had to dig through the interface to find this: https://github.com/tweag/rules_haskell/actions/runs/2657527636

**Comment by k1nkreet** [comment]
Turned out bindist configuration (which is the mostly demanding for disk size) exceeds the disk size on CI-runners now. Every bindist Bazel project generates about 4.6Gb of Bazel cache. With our strategy of creating separate workspace for every Bazel version, we need now N * 4.6 Gb (where N is a number of Bazel versions to test) space only for integration testing. In this PR we are trying to test 4 of them. So either we have to increase disk size on test runners or decrease the number of Bazel versions we are testing. @aherrmann How the CI runners are allocated? Is there any way to increase storage size for them?

**Comment by aherrmann** [comment]
> @aherrmann How the CI runners are allocated? Is there any way to increase storage size for them?

They are [hosted by Github](https://github.com/tweag/rules_haskell/blob/82d1f44e88a726b0eb00ac30a68d63012dc78c70/.github/workflows/workflow.yaml#L14). AFAIK, there is no direct way to increase the disk size.

**Comment by brendanhay** [comment]
There's only a 14GB SSD available on the GH runners and you won't be able to get that increased unless they raise the limit for the entire product.

That said, if you look at the start of the CI job log you can expand the steps: `Set up job` -> `Virtual Environment` -> `Included Software:` https://github.com/actions/virtual-environments/blob/ubuntu20/20220710.1/images/linux/Ubuntu2004-Readme.md 

This markdown file contains a list of [installed software](https://github.com/actions/virtual-environments/blob/ubuntu20/20220710.1/images/linux/Ubuntu2004-Readme.md#installed-software) which is quite extensive.

You could run some variation of the following to free up space prior to running other steps in the workflow via:

```yaml
    steps:
      - if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |-
          sudo swapoff -a
          sudo rm -rf /swapfile /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo apt clean
          docker rmi $(docker images -q) -f
```

Deleting dotnet and android in [my own workflows](https://github.com/brendanhay/amazonka/blob/0d70474d888c5e5a43417ac9f7b408e7890ff853/.github/workflows/build.yml#L30-L33) reclaimed a few more GB from the base image - maybe this would be sufficient to squeeze in one more testable version?

**Review by aherrmann — APPROVED** [review]
Thank you for debugging and fixing this!

> Probably I should drop a note somewhere in comments about it.

Yes, please! :slightly_smiling_face: 

> Maybe at some point it will force us to test one version per major version.

We'll probably also want to cap the number of past major versions that we test / are compatible with. Use of a new feature is a natural cause, but even without, it makes sense to not go too far back.

**Pull request merged**
