### PR TITLE
Use remote HTTP cache on CI

### PR DESCRIPTION
**Pull request by mrkkrp**
Once the corresponding infrastructure changes are merged (https://github.com/tweag/infra/pull/65), this enables using
google storage bucket for caching instead of caching to the local disk.

### CODE REVIEW

**Comment by mboes** [comment]
Have you looked at performance impact, if any?

**Comment by mrkkrp** [comment]
First run from scratch takes about 60 minutes (actually I might need to bump the limits). Subsequent runs are between 4 and 5 minutes and the state of the running instance does not affect the times, so everything is taken from the remote cache.

**Comment by mrkkrp** [comment]
That said, we'll need to setup NixOS cache before we can switch to ephemeral instances, so it's just the first step towards that goal.

**Comment by mboes** [comment]
60 minutes every 24 hours is a tough price to pay (ephemeral instances get scratched at least once every 24 hours). The number of PR's per day isn't high, so we'll be hitting that common case pretty frequently.

**Comment by mrkkrp** [comment]
This is now only blocked on the Windows failure. I do not understand what is going wrong there.

**Comment by mrkkrp** [comment]
As discussed, the windows failure is unrelated to this PR, so we might as well merge it.

**Pull request merged**
