### PR TITLE
Adding haskell-language-server 0.4

### PR DESCRIPTION
**Pull request by teto**
I wanted to give a spin to hls but this fails with
```
bazel run @hls-unpinned//:pin
Starting local Bazel server and connecting to it...
INFO: Repository hls-unpinned instantiated at:
  /home/teto/nova/rules_haskell/WORKSPACE:120:15: in <toplevel>
  /home/teto/.cache/bazel/_bazel_teto/b20af51f549240b69085971f497f86fc/external/rules_haskell/haskell/cabal.bzl:2236:29: in stack_snapshot
Repository rule _stack_snapshot_unpinned defined at:
  /home/teto/.cache/bazel/_bazel_teto/b20af51f549240b69085971f497f86fc/external/rules_haskell/haskell/cabal.bzl:1891:43: in <toplevel>
ERROR: An error occurred during the fetch of repository 'hls-unpinned':
   Traceback (most recent call last):
	File "/home/teto/.cache/bazel/_bazel_teto/b20af51f549240b69085971f497f86fc/external/rules_haskell/haskell/cabal.bzl", line 1644
		_resolve_packages(<6 more arguments>)
	File "/home/teto/.cache/bazel/_bazel_teto/b20af51f549240b69085971f497f86fc/external/rules_haskell/haskell/cabal.bzl", line 1149, in _resolve_packages
		_execute_or_fail_loudly(<2 more arguments>)
	File "/home/teto/.cache/bazel/_bazel_teto/b20af51f549240b69085971f497f86fc/external/rules_haskell/haskell/private/workspace_utils.bzl", line 18, in _execute_or_fail_loudly
		fail(<1 more arguments>)
Command failed: /home/teto/.cache/bazel/_bazel_teto/b20af51f549240b69085971f497f86fc/external/rules_haskell_stack/stack ls dependencies json --global-hints --external
Cloning 0a18edde24923251a148cbbc0ae993a6aac83b9c from https://github.com/haskell/haskell-language-server.git
No cabal file found for Repo from https://github.com/haskell/haskell-language-server.git, commit 0a18edde24923251a148cbbc0ae993a6aac83b9c in subdir ./hls-plugin-api
ERROR: Traceback (most recent call last):
	File "/home/teto/.cache/bazel/_bazel_teto/b20af51f549240b69085971f497f86fc/external/rules_haskell/haskell/cabal.bzl", line 1644
		_resolve_packages(<6 more arguments>)
	File "/home/teto/.cache/bazel/_bazel_teto/b20af51f549240b69085971f497f86fc/external/rules_haskell/haskell/cabal.bzl", line 1149, in _resolve_packages
		_execute_or_fail_loudly(<2 more arguments>)
	File "/home/teto/.cache/bazel/_bazel_teto/b20af51f549240b69085971f497f86fc/external/rules_haskell/haskell/private/workspace_utils.bzl", line 18, in _execute_or_fail_loudly
		fail(<1 more arguments>)
Command failed: /home/teto/.cache/bazel/_bazel_teto/b20af51f549240b69085971f497f86fc/external/rules_haskell_stack/stack ls dependencies json --global-hints --external
Cloning 0a18edde24923251a148cbbc0ae993a6aac83b9c from https://github.com/haskell/haskell-language-server.git
No cabal file found for Repo from https://github.com/haskell/haskell-language-server.git, commit 0a18edde24923251a148cbbc0ae993a6aac83b9c in subdir ./hls-plugin-api
INFO: Elapsed time: 11.232s
```
Seems like stack doesn't download the submodules ? I dont know how to check: where is downloaded the temporary clone in order to check ?

### CODE REVIEW

**Comment by mboes** [comment]
Could you say more about your solution? I take it having a dedicated snapshot is necessary? If so, why? Also, the number of necessary extra-deps looks high. Why is that?

**Comment by teto** [comment]
haskell-language-server is not available on stackage, so far I haven't got a solution really, Even if you remove all extra-deps, you will still get the error.

**Comment by mboes** [comment]
OK makes sense. And why do we want to build haskell-language-server in the rules_haskell workspace? What is the snapshot used by? I don't see any users of `@hls` in this PR, not even tests.

**Comment by aherrmann** [comment]
```
No cabal file found for Repo from https://github.com/haskell/haskell-language-server.git, commit 0a18edde24923251a148cbbc0ae993a6aac83b9c in subdir ./hls-plugin-api
```
At the pinned `haskell-language-server` commit 0a18edde24923251a148cbbc0ae993a6aac83b9c `hls-plugin-api` does not exist, see https://github.com/haskell/haskell-language-server/tree/0a18edde24923251a148cbbc0ae993a6aac83b9c . Removing that subdir from the custom snapshot fixes that particular issue.

---

Using `git: https://github.com/haskell/haskell-language-server.git` unfortunately means that you won't benefit from full repository caching, as `stack_snapshot` pinning currently cannot pin git or mercurial dependencies. Using `github` instead would look like this:
```
- github: haskell/haskell-language-server
  commit: 0a18edde24923251a148cbbc0ae993a6aac83b9c
  subdirs:
    - .
    - ./ghcide/
```
This produces the following error (I think you identified that issue already):
```
No cabal file found for Archive from https://github.com/haskell/haskell-language-server/archive/0a18edde24923251a148cbbc0ae993a6aac83b9c.tar.gz in subdir ./ghcide/
```
This is indeed because the submodule is not fetched, however this is not so much a restriction of `stack` as it is a restriction of the GitHub API. The provided tarball does not contain submodules. You can confirm this as follows
```
$ curl -L https://github.com/haskell/haskell-language-server/archive/0a18edde24923251a148cbbc0ae993a6aac83b9c.tar.gz | tar tvz | grep ghcide
drwxrwxr-x root/root         0 2020-09-03 21:58 haskell-language-server-0a18edde24923251a148cbbc0ae993a6aac83b9c/ghcide/
```
I.e. the `ghcide` subdir is empty.

You can work around this issue by declaring `ghcide` as a seperate package in the custom snapshot. I.e.
```
packages:
- github: haskell/haskell-language-server
  commit: 0a18edde24923251a148cbbc0ae993a6aac83b9c
- github: haskell/ghcide
  commit: ceb332c9b51ba46a5a3b841caa370d939d1351bc
...
```

With these changes `bazel run @hls-unpinned//:pin` succeeds.

---

To expand on @mboes's question

> And why do we want to build haskell-language-server in the rules_haskell workspace? What is the snapshot used by? I don't see any users of `@hls` in this PR, not even tests.

If you intend to use hls in your own project, then there is no need to add it to rules_haskell's `WORKSPACE` file. In fact Bazel will effectively ignore rules_haskell's `WORKSPACE` file in the context of another project that depends on rules_haskell.

**Comment by teto** [comment]
thanks for looking into it. So actually I first tried to add this to our own (closed source) project and opened the PR just as a convenient way to share the changes. I don't know if it's within the scope of rules_haskell to have this (but it alreay has ghcide ).

Doing 
```
packages:
- github: haskell/haskell-language-server
  commit: 0a18edde24923251a148cbbc0ae993a6aac83b9c
- github: haskell/ghcide
  commit: ceb332c9b51ba46a5a3b841caa370d939d1351bc
```
was my ultimate backup.

> Using git: https://github.com/haskell/haskell-language-server.git unfortunately means that you won't benefit from full repository caching, as stack_snapshot pinning currently cannot pin git or mercurial dependencies.

That explains why i could not pin some other snapshot ! glad to know thanks !

I had first tried `github:` and realized it hadn't submodules (same in nix), which is why I switched to `git:`. From the stack tracker, it  seemed like it was fetching the submodules but I was not 100% sure, which is why I haven't realized I had changed the revision and `hls-plugin-api` was not needed anymore. Sorry for bothering you, hopefully the thread can help others.

**Comment by aherrmann** [comment]
> So actually I first tried to add this to our own (closed source) project and opened the PR just as a convenient way to share the changes. I don't know if it's within the scope of rules_haskell to have this (but it alreay has ghcide ).

Thanks for clarifying. Yes, given the [recent recommendation](http://neilmitchell.blogspot.com/2020/09/dont-use-ghcide-anymore-directly.html) to use hls instead of using ghcide directly, it would be good to update rules_haskell accordingly. I.e. use hls instead of ghcide and also update the documentation and tests to point to hls. Though, users of rules_haskell do not have to wait for this to happen in rules_haskell, they can update to hls independently.

> Sorry for bothering you, hopefully the thread can help others.

There's nothing to apologize for. Thanks for raising the issue, as you say it is useful to have these kinds of build issues documented.

**Pull request closed without merging**
