### PR TITLE
Allow @ in Haskell binary names

### LINKED ISSUE #962: @ in rule name
**Describe the bug**

A rule name with an `@` was used to be accepted, and it is not anymore.

For example, in current master:

```
haskell_binary(
    name = "foo@bar",
    srcs = ["Foo.hs"],
)
```

Leads to the following build failure:

```
[nix-shell:~/tweag/rules_haskell]$ bazel build //tests:foo@bar
INFO: Build option --test_env has changed, discarding analysis cache.
INFO: Analyzed target //tests:foo@bar (1 packages loaded, 1082 targets configured).
INFO: Found 1 target...
ERROR: /home/guillaume/tweag/rules_haskell/tests/BUILD.bazel:347:1: HaskellRegisterPackage tests/link-config-foo@bar/link-config-foo@bar.conf failed (Exit 1) ghc-pkg failed: error executing command external/io_tweag_rules_haskell_ghc_nixpkgs/bin/ghc-pkg recache '--package-db=bazel-out/k8-fastbuild/bin/tests/link-config-foo@bar' -v0 --no-expand-pkgroot

Use --sandbox_debug to see verbose messages from the sandbox
ghc-pkg: 0: Parse of field '
unexpected '@'
expecting "-", white space or end of input

link-config-foo@bar
' failed.
Target //tests:foo@bar failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.567s, Critical Path: 0.16s
INFO: 15 processes: 15 linux-sandbox.
FAILED: Build did NOT complete successfully
```

Workaround: rename the rules.

Is this a bug or a requirement of rule name?

### PR DESCRIPTION
**Pull request by aherrmann**
Closes #962.
Fixes a regression introduced in #930.

Note, the Bazel documentation [specifies](https://docs.bazel.build/versions/master/build-ref.html#name)

> Target names must be composed entirely of characters drawn from the set `a–z`, `A–Z`, `0–9`, and the punctuation symbols `_/.+-=,@~`.

Currently, most of these are not supported by rules_haskell.

A possible solution would be to implement full [z-encoding](https://hackage.haskell.org/package/ghc-8.4.3/docs/src/Encoding.html#zEncodeString) in rules_haskell and add a case for `@`. Also, `ghc-pkg` does not allow more than one `-` in a row, so simply replacing characters by `-` can generate invalid package names.

### CODE REVIEW

**Comment by guibou** [comment]
> Do you have a use case where you really want @ in the binary name?

On a client codebase we use `@` for many extended targets. We can easily replace it by something else (note: as @aherrmann stated, we need to be careful about avoiding repetition of these chars, because they are replaced by `-`).

We can avoid this char, we just need to refactor on our side.

**Comment by mboes** [comment]
I'd vote for banning `@`, owing to that character being used for companion targets. @aherrmann what do you think?

**Comment by guibou** [comment]
@mboes 

That's ok for me, that's not a huge refactoring. I just need to find a better symbol.

**Comment by aherrmann** [comment]
Generally I'm in favor of banning special characters to avoid too much complexity in the implementation. 

Though, the `@` character is convenient to have available as a user. E.g. in the `daml` repo we generate an implicit `@ghci` `haskell_repl` target for every Haskell target, which nicely matches the builtin `@xyz` targets. But it should be easy to replace that with another character when necessary, and reserving `@` for `rules_haskell` makes sense.

**Comment by mboes** [comment]
OK I guess that's convincing. No need for rules_haskell to hog that namespace exclusively.

**Pull request merged**
