### PR TITLE
Set stub_shebang in bindist Python toolchain

### PR DESCRIPTION
**Pull request by aherrmann**
Closes https://github.com/tweag/rules_haskell/issues/1173

This is the bindist analog of the rules_nixpkgs solution here: https://github.com/tweag/rules_nixpkgs/pull/174

### CODE REVIEW

**Review by Xophmeister — APPROVED** [review]

**Comment by meteorcloudy** [comment]
This change is causing rules_haskell to break with Bazel@HEAD, we'll lose test coverage for you :(
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2375#73315dac-a9aa-49b4-bee1-38507d2f86ab
```
(04:04:06) ERROR: An error occurred during the fetch of repository 'rules_haskell_python_local':
   Traceback (most recent call last):
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/afd0e027d4dc894108ae8f85e604d52d/external/rules_haskell/haskell/ghc_bindist.bzl", line 774, column 28, in _configure_python3_toolchain_impl
		if versions.is_at_least("4.2.0", versions.get()):
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/afd0e027d4dc894108ae8f85e604d52d/external/bazel_skylib/lib/versions.bzl", line 80, column 32, in _is_at_least
		return _parse_bazel_version(version) >= _parse_bazel_version(threshold)
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/afd0e027d4dc894108ae8f85e604d52d/external/bazel_skylib/lib/versions.bzl", line 55, column 22, in _parse_bazel_version
		return tuple([int(n) for n in version.split(".")])
Error in int: empty string
```

**Comment by meteorcloudy** [comment]
Looks like [_is_at_least](https://github.com/bazelbuild/bazel-skylib/blob/main/lib/versions.bzl#L69) in bazel-skylib isn't compatible with unreleased Bazel version, so you can probably check `versions.get()` before passing to it.

**Comment by aherrmann** [comment]
@meteorcloudy Thank you for reporting and looking into the issue. You're spot-on, I was able to reproduce the failure locally with `USE_BAZEL_VERSION=last_green` and fixing that line removes that issue.
It turns out that Skylib has [`versions.check`](https://github.com/bazelbuild/bazel-skylib/blob/e30197f3799eb038fbed424e365573f493d52fa5/lib/versions.bzl#L82) which handles this case already.l

**Comment by meteorcloudy** [comment]
But `_check_bazel_version` will fail if the version isn't in range, but I guess you already noticed..

**Comment by aherrmann** [comment]
> But `_check_bazel_version` will fail if the version isn't in range, but I guess you already noticed..

Indeed, I shot too quickly there. :man_facepalming: 

https://github.com/tweag/rules_haskell/pull/1707 should hopefully fix it.

**Pull request merged**
